#!/usr/bin/env bash

# Statusbar
eww daemon &
eww open bar &

# Wallpaper
hyprpaper &

# Terminal
foot --server &

# Polkit agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Notification daemon
pkill dunst &
dunst &

# Kill any running thunar instance and run daemon
pkill thunar &
thunar -q &
thunar --daemon &

# Automatic disk mounting
udiskie &
