#!/usr/bin/env bash

# Statusbar
eww daemon &
eww open bar &

# Wallpaper
hyprpaper &

# Terminal
foot --server &

# Notification daemon
pkill dunst &
dunst &

# Kill any running thunar instance and run daemon
thunar -q &
thunar --daemon &
